emit:
  - "@typespec/json-schema"
options:
  "@typespec/json-schema":
    file-type: json
    bundleId: "https://schemas.heritage-science.dev/HeritageDataPackage"
    emitter-output-dir: "{project-root}/schemas"
