# generated by datamodel-codegen:
#   filename:  heritage-data-package-inlined.json
#   timestamp: 2026-06-08T16:23:38+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, RootModel


class HeritageDataPackage(RootModel[Any]):
    root: Any


class MaterialClass(RootModel[Any]):
    root: Any


class RelationshipType(RootModel[Any]):
    root: Any


class SampleType(RootModel[Any]):
    root: Any


class UnitType(RootModel[Any]):
    root: Any


class Datetime(RootModel[Any]):
    root: Any


class FieldId(RootModel[Any]):
    root: Any


class Uuid(RootModel[Any]):
    root: Any


class SiteMetadata(BaseModel):
    projectId: Uuid
    projectName: str
    jurisdiction: str | None = None
    gridReference: str | None = None
    epsgCode: int | None = Field(None, ge=-2147483648, le=2147483647)
    director: str | None = None
    siteCode: str | None = None
    excavationYear: str | None = None
    createdAt: Datetime | None = None
    updatedAt: Datetime | None = None


class StratigraphicUnit(BaseModel):
    id: Uuid
    contextNumber: FieldId
    unitType: UnitType
    description: str | None = None
    interpretation: str | None = None
    period: str | None = None
    phase: str | None = None
    length_m: float | None = None
    width_m: float | None = None
    depth_m: float | None = None
    mediaPresent: bool | None = None
    confidence: float | None = None
    findIds: list[Uuid] | None = None
    sampleIds: list[Uuid] | None = None


class StratigraphicRelationship(BaseModel):
    id: Uuid
    sourceId: Uuid
    targetId: Uuid
    relationshipType: RelationshipType
    confidence: float | None = None
    notes: str | None = None


class Find(BaseModel):
    id: Uuid
    contextId: Uuid
    findNumber: str | None = None
    materialClass: MaterialClass
    typology: str | None = None
    count: int | None = Field(None, ge=-2147483648, le=2147483647)
    weight_g: float | None = None
    period: str | None = None
    description: str | None = None
    recorded: bool | None = None


class Sample(BaseModel):
    id: Uuid
    contextId: Uuid
    sampleId: str | None = None
    sampleType: SampleType
    volume_l: float | None = None
    weight_g: float | None = None
    notes: str | None = None


class Chronology(BaseModel):
    id: Uuid
    sampleId: Uuid | None = None
    contextId: Uuid | None = None
    labCode: str | None = None
    uncalBp: int | None = Field(None, ge=-2147483648, le=2147483647)
    error: int | None = Field(None, ge=-2147483648, le=2147483647)
    calibrationCurve: str | None = None
    calibratedRange68: str | None = None
    calibratedRange95: str | None = None
    datingMethod: str | None = None
    datedMaterial: str | None = None
    delta13C: float | None = None


class DigitalAsset(BaseModel):
    id: Uuid
    contextId: Uuid | None = None
    filePath: str
    assetType: str
    mimeType: str | None = None
    fileSizeBytes: str | None = None
    checksumSha256: str | None = None
    caption: str | None = None
    orientation: str | None = None
    scale: str | None = None


class HeritageDataPackage1(BaseModel):
    schemaVersion: str
    createdAt: Datetime
    provenance: str | None = None
    metadata: SiteMetadata | None = None
    contexts: list[StratigraphicUnit]
    relationships: list[StratigraphicRelationship]
    finds: list[Find]
    samples: list[Sample]
    dates: list[Chronology]
    assets: list[DigitalAsset]
