# generated by datamodel-codegen:
#   filename:  tmp5e_z7on8.json
#   timestamp: 2026-06-22T02:15:20+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field, RootModel


class HDP(RootModel[Any]):
    root: Any


class Uuid(RootModel[str]):
    root: str = Field(
        ..., pattern='^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )


class Datetime(RootModel[str]):
    root: str


class FieldId(RootModel[str]):
    root: str = Field(..., pattern='^\\[?[A-Za-z0-9]+\\]?$')


class SchemaVer(RootModel[str]):
    root: str = Field(..., pattern='^\\d+-\\d+-\\d+$')


class UnitType(StrEnum):
    Deposit = 'Deposit'
    Cut = 'Cut'
    Interface = 'Interface'
    Masonry = 'Masonry'
    Natural = 'Natural'
    Unknown = 'Unknown'


class RelationshipType(StrEnum):
    Above = 'Above'
    Below = 'Below'
    Equals = 'Equals'
    Contemporary = 'Contemporary'
    Cuts = 'Cuts'
    Fills = 'Fills'


class MaterialClass(StrEnum):
    Pottery = 'Pottery'
    Bone = 'Bone'
    Flint = 'Flint'
    Metal = 'Metal'
    CBM = 'CBM'
    Glass = 'Glass'
    Shell = 'Shell'
    Slag = 'Slag'
    Wood = 'Wood'
    Textile = 'Textile'
    Leather = 'Leather'
    Environmental = 'Environmental'
    Other = 'Other'


class SampleType(StrEnum):
    Radiocarbon = 'Radiocarbon'
    Environmental = 'Environmental'
    Isotopic = 'Isotopic'
    Dendrochronology = 'Dendrochronology'
    Archaeomagnetic = 'Archaeomagnetic'
    OSL = 'OSL'
    Other = 'Other'


class AgentType(StrEnum):
    Human = 'Human'
    AIModel = 'AIModel'
    Software = 'Software'


class SiteMetadata(BaseModel):
    projectId: Uuid
    projectName: str
    jurisdiction: str | None = None
    gridReference: str | None = None
    epsgCode: int | None = Field(None, ge=-2147483648, le=2147483647)
    director: str | None = None
    siteCode: str | None = None
    excavationYear: str | None = None
    createdAt: Datetime | None = None
    updatedAt: Datetime | None = None


class StratigraphicUnit(BaseModel):
    id: Uuid
    contextNumber: FieldId
    unitType: UnitType
    description: str | None = None
    interpretation: str | None = None
    period: str | None = None
    phase: str | None = None
    length_m: float | None = None
    width_m: float | None = None
    depth_m: float | None = None
    mediaPresent: bool | None = None
    confidence: float | None = None
    findIds: list[Uuid] | None = None
    sampleIds: list[Uuid] | None = None


class StratigraphicRelationship(BaseModel):
    id: Uuid
    sourceId: Uuid
    targetId: Uuid
    relationshipType: RelationshipType
    confidence: float | None = None
    notes: str | None = None


class Find(BaseModel):
    id: Uuid
    contextId: Uuid
    findNumber: str | None = None
    materialClass: MaterialClass
    typology: str | None = None
    count: int | None = Field(None, ge=-2147483648, le=2147483647)
    weight_g: float | None = None
    period: str | None = None
    description: str | None = None
    recorded: bool | None = None


class Sample(BaseModel):
    id: Uuid
    contextId: Uuid
    sampleId: str | None = None
    sampleType: SampleType
    volume_l: float | None = None
    weight_g: float | None = None
    notes: str | None = None


class Chronology(BaseModel):
    id: Uuid
    sampleId: Uuid | None = None
    contextId: Uuid | None = None
    labCode: str | None = None
    uncalBp: int | None = Field(None, ge=-2147483648, le=2147483647)
    error: int | None = Field(None, ge=-2147483648, le=2147483647)
    calibrationCurve: str | None = None
    calibratedRange68: str | None = None
    calibratedRange95: str | None = None
    datingMethod: str | None = None
    datedMaterial: str | None = None
    delta13C: float | None = None


class DigitalAsset(BaseModel):
    id: Uuid
    contextId: Uuid | None = None
    filePath: str
    assetType: str
    mimeType: str | None = None
    fileSizeBytes: str | None = None
    checksumSha256: str | None = None
    caption: str | None = None
    orientation: str | None = None
    scale: str | None = None


class ProvenanceAgent(BaseModel):
    id: Uuid
    agentType: AgentType
    name: str
    version: str | None = None
    modelId: str | None = None


class ProvenanceActivity(BaseModel):
    id: Uuid
    activityType: str
    startedAtTime: Datetime | None = None
    agent: ProvenanceAgent


class ProvenanceRecord(BaseModel):
    entity: Uuid
    wasGeneratedBy: ProvenanceActivity | None = None
    wasAttributedTo: ProvenanceAgent | None = None
    generatedAtTime: Datetime
    confidence: float | None = Field(None, ge=0.0, le=1.0)
    notes: str | None = None


class HeritageDataPackage(BaseModel):
    schemaVersion: SchemaVer
    createdAt: Datetime
    updatedAt: Datetime | None = None
    provenance: str | None = None
    provenanceLog: list[ProvenanceRecord] | None = None
    metadata: SiteMetadata | None = None
    contexts: list[StratigraphicUnit]
    relationships: list[StratigraphicRelationship]
    finds: list[Find]
    samples: list[Sample]
    dates: list[Chronology]
    assets: list[DigitalAsset]